### ISSUE TITLE
Discussion - packaging meson (>=0.62) under ubuntu 18.04

### ISSUE THREAD

**Issue by souravdas142** [savoury1/ubuntu-rolling#2]
Hi @savoury1 ,

Thank you for your support for packaging everything to the newest possible version. Currently we are facing an issue to package meson 0.62 and later version under ubuntu 18.04. Though I tried to build at https://launchpad.net/~pipewire-debian/+archive/ubuntu/testing/+build/24107160. But some error came like 
```bash
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib/python3.8/abc.py", line 64, in <module>
ModuleNotFoundError: No module named '_abc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/io.py", line 52, in <module>
  File "/usr/lib/python3.8/abc.py", line 68, in <module>
  File "/usr/lib/python3.8/_py_abc.py", line 35
    def __new__(mcls, name, bases, namespace, /, **kwargs):
                                              ^
SyntaxError: invalid syntax
dh_auto_build: pybuild --build died with signal 6
debian/rules:37: recipe for target 'binary' failed
```

Already we know meson (>=0.62) need python (>= 3.7). And ubuntu 18.04 officaly deliver python 3.6.9 and if I tried to install python 3.8, there is no way I can make it possible to build it. Can you please help us to make it available to user ? 

Any way can we make it possible to package ? otherwise many project will not build in future. 
Waiting for your positive reply. Thank you.

Kind regards,
Sourav

**Comment by savoury1** [comment]
Hi @souravdas142,

Glad to hear you are finding the updated versions of software that I package useful. In regards to Meson 0.62 so far I have not needed it for any of my own builds, as 0.61.x has been sufficient for everything that I package. With such critical software I am always cautious about jumping to the latest versions, in case this breaks the builds of older software not updated to use the newer syntax, etc, of a newer build tool.

So for now I will be staying on the Meson 0.61.x LTS branch (0.61.x was declared LTS recently) and an update to version 0.61.5 is now available at ppa:savoury1/build-tools. At such time that I do encounter software that I am packaging which requires Meson >= 0.62 then I will update to that version.

If you do need Meson 0.62 now for some of your own packaging then I suggest you take a look first at the Xenial packaging for Meson 0.61.5 at my PPA which is built with Python 3.6 (Xenial ships with Python 3.5). You can try building Meson 0.62 for Bionic against a new PPA that I've made this past week, ppa:savoury1/python-defaults-3.7, and you would need to make appropriate changes to the packaging code for use of Python 3.7 (instead of 3.6).

Cheers, Rob

**Comment by souravdas142** [comment]
@savoury1

Thank you for your kind help :smiley: :handshake: 
 > If you do need Meson 0.62 now for some of your own packaging then I suggest you take a look first at the Xenial packaging for Meson 0.61.5 at my PPA which is built with Python 3.6 (Xenial ships with Python 3.5). You can try building Meson 0.62 for Bionic against a new PPA that I've made this past week, ppa:savoury1/python-defaults-3.7, and you would need to make appropriate changes to the packaging code for use of Python 3.7 (instead of 3.6).

Yeah sure, I will check this out. This is really helpful having a reference. Thank you again.
